/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Editfees extends javax.swing.JFrame {

    /**
     * Creates new form Editfees
     */
    public Editfees() {
        initComponents();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Record of the all Student Fees");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt No", "Student Name", "Payment Mode", "Cheque No", "Bank Name", "DD No", "Course Name", "Total Amount", "Amount", "CGST", "SGST", "Total in Words", "Remark", "Year 1", "Year 2"
            }
        ));
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 780, 190));

        jButton3.setText("Back");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        try {
         Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement("update FEES_DETAILS SET RECIEPT_NO = ?, STUDENT_NAME = ?, PAYMENT_MODE = ?, CHEQUE_NO = ?, BANK_NAME = ?, DD_NO = ?, COURSE_NAME = ?, TOTAL_AMOUNT = ?, AMOUNT = ?, CGST = ?, SGST = ?, TOTAL_IN_WORDS = ?, REMARK = ?, YEAR1 = ?, YEAR2 = ? WHERE RECIEPT_NO = ?");
         
         DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
         
         for (int i = 0; i < tm.getRowCount(); i++) {
          pst.setInt(1, (int) tm.getValueAt(i, 0));
          pst.setString(2, (String) tm.getValueAt(i, 1));   
          pst.setString(3, (String) tm.getValueAt(i, 2));
          pst.setString(4, (String) tm.getValueAt(i, 3));
          pst.setString(5, (String) tm.getValueAt(i, 4));
          pst.setString(6, (String) tm.getValueAt(i, 5));       
          pst.setString(7, (String) tm.getValueAt(i, 6));
          pst.setDouble(8, (double) tm.getValueAt(i, 7));
          pst.setDouble(9, (double) tm.getValueAt(i, 8));
          pst.setDouble(10, (double) tm.getValueAt(i, 9));
          pst.setDouble(11, (double) tm.getValueAt(i, 10));
          pst.setString(12, (String) tm.getValueAt(i, 11));
          pst.setString(13, (String) tm.getValueAt(i, 12));
          pst.setInt(14, (int) tm.getValueAt(i, 13));
          pst.setInt(15, (int) tm.getValueAt(i, 14));
          pst.setInt(16, (int) tm.getValueAt(i, 0));
          
          pst.executeUpdate();
         }
        }
        catch(SQLException e){ 
        }
    }//GEN-LAST:event_jTable1PropertyChange

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    home h = new home();
    h.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void display() {
        
       
        try
        {
         Connection con = DBConnection.getConnection();
         PreparedStatement pst = con.prepareStatement("select * from fees_Details");
               
         ResultSet rs = pst.executeQuery();
         
         ResultSetMetaData rm = rs.getMetaData();
         DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
         
         int count = rm.getColumnCount();
         
         tm.setRowCount(0);
         
         while(rs.next()) {
             Vector v = new Vector();
             for(int i = 0 ; i <= count ; i++) {
                 v.add(rs.getInt("Reciept_No"));
                 v.add(rs.getString("Student_Name"));
                 v.add(rs.getString("Payment_Mode"));
                 v.add(rs.getString("Cheque_NO"));
                 v.add(rs.getString("Bank_Name"));
                 v.add(rs.getString("DD_No"));
                 v.add(rs.getString("Course_Name"));
                 v.add(rs.getDouble("Total_Amount"));
                 v.add(rs.getDouble("Amount"));
                 v.add(rs.getDouble("CGST"));
                 v.add(rs.getDouble("SGST"));
                 v.add(rs.getString("Total_In_Words"));
                 v.add(rs.getString("Remark"));
                 v.add(rs.getInt("Year1"));
                 v.add(rs.getInt("Year2"));
             }
             
             tm.addRow(v);
         }
         
        }
        catch(SQLException e){ 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editfees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editfees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
